nptl: remove unneeded libc-lock.h include
I semi-accidentally added include for libc-lock.h because the intention
was to use locking macroes from there. However, we ended up using using
the weak alias stuff. This is additionally good since now this can result
in compile errors like:

In file included from /toolchain/include/bits/uClibc_mutex.h:16,
                 from /toolchain/include/bits/uClibc_stdio.h:107,
                 from /toolchain/include/stdio.h:72,
                 from /work/freetype-2.3.11/include/freetype/config/ftstdlib.h:100,
                 from ./builds/unix/ftconfig.h:43,
                 from builds/unix/ftsystem.c:21:
/toolchain/include/bits/libc-lock.h:309: error: expected '=', ',',
';', 'asm' or '__attribute__' before 'void'

Remove the unneeded include causing breakage.

Reported-by: Kevin Day <thekevinday@gmail.com>
Signed-off-by: Timo Teräs <timo.teras@iki.fi>
Signed-off-by: Austin Foxley <austinf@cetoncorp.com>