Amir Shalem writes: there are missing prototypes for chown() and execle() in uClibc-snapshot. I'm attaching a patch to add the missing prototypes.
the error I'm getting without the patch:
      AR cr libc/libc_so.a
      LD libuClibc-0.9.28.so
    libc/libc_so.a(grantpt.os): In function `__unix_grantpt':
    grantpt.c:(.text+0x108): undefined reference to `__GI_chown'
    grantpt.c:(.text+0x1ae): undefined reference to `__GI_execle'