Paul Brook writes: When building an arm-uclinux toolchain withthreading disabled I get:
libc/stdio/getchar.c:26: error: 'getchar' aliased to undefined 
symbol 'getchar_unlocked'

It looks like it's missing libc_hidden_def(getchar_unlocked). Patch below 
fixes this.