ldso_sh: Provide only one definition for elf_machine_type_class
It doesn't need to provide different definition of elf_machine_type_class
macro depending on TLS support.
It also fixes build for sh architecture when thread support is off:
  CC ldso/ldso/ldso.oS
In file included from ./ldso/ldso/sh/dl-sysdep.h:9,
                 from ./ldso/include/dl-string.h:11,
                 from ./ldso/include/ldso.h:40,
                 from ldso/ldso/ldso.c:33:
./include/tls.h:6:22: error: tls.h: No such file or directory
make: *** [ldso/ldso/ldso.oS] Error 1

Signed-off-by: Carmelo Amoroso <carmelo.amoroso@st.com>